/* == Generated by Matrix67.com == */

     #include      <stdio.h>
   main(t ,_,a)  char*a;{return
 t<1?main(*a,a[-t],"=a-1kj3gnm:q\
ebh_cf*<r.d>i^+?,()[?qzyrjuvcdefg\
h,!kbpolwxs'.t main(")&&a[-t]&&main
(t-1,_,a):t/2?_==*a?putchar(32[a])
  :_%115<36||main(t,_,a+1):main(
    0,t,"~)?r<g:?1<3y?+<?m:(x\
      +ub}_?1<3?(k:?+b:}?n3\
        +z:>+?([m?{>.::+:\
          >}+?e)kr?)ig:\
            t?:g#:k?,\
              :+^}")
                ;}
